<?php

	'web' => [
		'workspaces' => [
			'ACME',
			'Forward Thinking',
			'ASO Digital',
			'Keyline',
			'WTC Media',
			'RE-space',
			'Digital Creativity',
			'CRE8',
			'Teal Creative',
			'RD Development',
			'Smith Designs',
			'Turnaround Creative',
			'GRDM Print',
			'Rogers and Rogers',
			'Latitude Agency',
			'DA Brothers Design',
			'Spacious Designs',
			'Insight Ideas',
			'Elevate Media',
			'XIO',
		],
		'clients' => [
			'Aetna',
			'Lowes',
			'ConocoPhillips',
			'Intel',
			'Energy Transfer Equity',
			'Caterpillar',
			'Prudential Financial',
			'Pfizer',
			'Disney',
			'Humana',
			'Enterprise Products Partners',
			'Cisco Systems',
			'Sysco',
			'Ingram Micro',
			'Coca-Cola',
			'Lockheed Martin',
			'FedEx',
			'Johnson Controls',
			'Plains GP Holdings',
			'World Fuel Services',
			'CHS',
			'American Airlines Group',
			'Merck',
			'Best Buy',
			'Delta Air Lines',
			'Honeywell International',
			'HCA Holdings',
			'Goldman Sachs Group',
			'Tesoro',
			'Liberty Mutual',
			'United Continental Holdings',
			'New York Life Insurance',
			'Oracle',
			'Morgan Stanley',
			'Tyson Foods',
			'Safeway',
			'Nationwide',
			'Deere',
			'DuPont',
			'American Express',
			'Allstate',
			'Cigna',
			'Mondelez International',
			'TIAA-CREF',
			'INTL FCStone',
			'Mutual Life Insurance',
			'DirecTV',
			'Halliburton',
			'Twenty-First Century Fox',
			'3M',
			'Sears Holdings',
		],
		'projects' => [
			'Logo Re-design',
			'Rebranding',
			'Website Design'
			'Website Revamp',
			'Blog Campaign',
			'Update Flyers',
			'Wordpress Overhaul',
			'Drupal Migration',
			'CMS Build',
			'API Integration',
			'Zapier Integration',
			'Database Migration',
			'Database Indexing',
			'Marketing Material Relaunch',
			'Customer Research',
			'TPS Reports',
			'Code Review',
			'GitHub Migration',
			'Test Deployment',
			'Color Scheme Review',
		],
		'labels' => [
			'Branding',
			'Design',
			'Meetings',
			'Development',
			'Marketing',
			'Engineering',
			'Research',
			'Inbox',
			'In Review',
			'Pending Discussion',
			'For Review',
		],
		'tasks' => [
			'Logo design review',
			'Create logo paths',
			'Fix bug with component',
			'Complete review',
			'Fix bug with modal',
			'Create TPS overview',
			'Install dependencies',
			'Component build',
			'Staff meeting',
			'Notes review',
			'Create outline document',
			'Daily standup',
			'Design main components',
			'Fix bug with browser extension',
			'Review weekly report',
			'Blog article outline',
			'Typography styles',
			'CSS restructure',
			'Convert to vectors',
			'Resize main assets',
			'Texturize blocks',
			'Meet with API team',
			'Setup with Axios',
			'Meeting with John',
			'Meeting with Sandra',
			'Team catchup',
			'Client call',
			'Rebuild Node server',
			'Document new resources',
			'API restructure',
			'Test connection methods',
			'Review new themes',
			'SASS restructuring',
			'Modal window build',
			'Fix resizing issue',
			'Demo new version to client',
			'Create slide deck',
			'Present new concept',
			'Google Analytics report',
			'Convert data to CSV',
			'Update stylesheets',
		]
	]

